# Hello World

In [1]:
import tensorflow as tf
c = tf.constant('Hello, world!')
with tf.Session() as sess:
    print(sess.run(c))

b'Hello, world!'


# Programming Concepts

In [13]:
x = tf.constant(5.2)
y = tf.Variable([0])
y = y.assign([5])

In [14]:
with tf.Session() as sess:
    initialization = tf.global_variables_initializer()
    print(y.eval())

[5]


In [15]:
g = tf.Graph()

with g.as_default():
    x = tf.constant(8, name='x_const')
    y = tf.constant(5, name='y_const')
    my_sum = tf.add(x, y, name='x_y_sum')
    
    with tf.Session() as sess:
        print(my_sum.eval())

13


# Exercise

In [16]:
with g.as_default():
    x = tf.constant(8, name='x_const')
    y = tf.constant(5, name='y_const')
    my_sum = tf.add(x, y, name='x_y_sum')
    
    z = tf.constant(4, name='z_const')
    
    new_sum = tf.add(my_sum, z, name='x_y_z_sum')
    
    with tf.Session() as sess:
        print(new_sum.eval())

17


In [18]:
with tf.Graph().as_default():
    primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
    
    ones = tf.ones([6], dtype=tf.int32)
    
    just_beyond_primes = tf.add(primes, ones)
    
    with tf.Session() as sess:
        print(just_beyond_primes.eval())

[ 3  4  6  8 12 14]


In [19]:
with tf.Graph().as_default():
    scalar = tf.zeros([])
    
    vector = tf.zeros([3])
    
    matrix = tf.zeros([2, 3])
    
    with tf.Session() as sess:
        print('scalar has shape', scalar.get_shape(), 'and value:\n', scalar.eval())
        print('vector has shape', vector.get_shape(), 'and value:\n', vector.eval())
        print('matrix has shape', matrix.get_shape(), 'and value:\n', matrix.eval())

scalar has shape () and value:
 0.0
vector has shape (3,) and value:
 [ 0.  0.  0.]
matrix has shape (2, 3) and value:
 [[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [27]:
with tf.Graph().as_default():
    primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
    
    ones = tf.constant(1, dtype=tf.int32)
        
    just_beyond_primes = tf.add(primes, ones)
        
    with tf.Session() as sess:
        print(just_beyond_primes.eval())

[ 3  4  6  8 12 14]


In [29]:
with tf.Graph().as_default():
    x = tf.constant([[5, 2, 4, 3], [5, 1, 6, -2], [-1, 3, -1, -2]], dtype=tf.int32)
    y = tf.constant([[2, 2], [3, 5], [4, 5], [1, 6]], dtype=tf.int32)
    
    matrix_multiple_result = tf.matmul(x, y)
    
    with tf.Session() as sess:
        print(matrix_multiple_result.eval())

[[35 58]
 [35 33]
 [ 1 -4]]


In [32]:
with tf.Graph().as_default():
    matrix = tf.constant([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12], [13, 14], [15,16]], dtype=tf.int32)

    reshaped_2x8_matrix = tf.reshape(matrix, [2, 8])
    
    reshaped_4x4_matrix = tf.reshape(matrix, [4, 4])
    
    with tf.Session() as sess:
        print("Original matrix (8x2):")
        print(matrix.eval())
        print("Reshaped matrix (2x8):")
        print(reshaped_2x8_matrix.eval())
        print("Reshaped matrix (4x4):")
        print(reshaped_4x4_matrix.eval())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped matrix (2x8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Reshaped matrix (4x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [34]:
with tf.Graph().as_default(), tf.Session() as sess:
    a = tf.constant([5, 3, 2, 7, 1, 4])
    b = tf.constant([4, 6, 3])
    
    a = tf.reshape(a, [2, 3])
    b = tf.reshape(b, [3, 1])
    
    mult = tf.matmul(a, b)
    
    print(mult.eval())

[[44]
 [46]]


In [44]:
g = tf.Graph()
with g.as_default():
    v = tf.Variable([3])
    w = tf.Variable(tf.random_normal([1], mean=1.0, stddev=0.35))

In [45]:
with g.as_default():
    with tf.Session() as sess:
        try:
            v.eval()
        except tf.errors.FailedPreconditionError as e:
            print('Caught expected error: ', e)

Caught expected error:  Attempting to use uninitialized value Variable
	 [[Node: _retval_Variable_0_0 = _Retval[T=DT_INT32, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]


In [59]:
with g.as_default():
    with tf.Session() as sess:
        initializer = tf.global_variables_initializer()
        sess.run(initializer)
        print(v.eval())
        print(w.eval())

[3]
[ 1.44004297]


In [65]:
with g.as_default():
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        print(w.eval())
        print(w.eval())
        print(w.eval())

[ 0.90975296]
[ 0.90975296]
[ 0.90975296]


In [66]:
with g.as_default():
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        print(v.eval())
        assignment = tf.assign(v, [7])
        print(v.eval())
        sess.run(assignment)
        print(v.eval())

[3]
[3]
[7]


# Exercise 2

Create a dice simulation, which generates a `10x3` 2-D tensor in which:

  * Columns `1` and `2` each hold one throw of one six-sided die (with values 1–6).
  * Column `3` holds the sum of Columns `1` and `2` on the same row.

For example, the first row might have the following values:

  * Column `1` holds `4`
  * Column `2` holds `3`
  * Column `3` holds `7`

You'll need to explore the [TensorFlow documentation](https://www.tensorflow.org/api_guides/python/array_ops) to solve this task.

In [94]:
g = tf.Graph()
with g.as_default():
    with tf.Session() as sess:
        a = tf.Variable(tf.random_uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
        b = tf.Variable(tf.random_uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
        c = tf.add(a, b)
        
        sess.run(tf.global_variables_initializer())
        
        final = tf.concat([a, b, c], axis=1)
         
        print(final.eval())
        

[[2 5 7]
 [6 3 9]
 [2 4 6]
 [3 6 9]
 [1 2 3]
 [4 3 7]
 [1 4 5]
 [1 4 5]
 [1 2 3]
 [6 2 8]]
